image: docker.cern.ch/flutter-dev/build:latest

test:
    script:
        - mkdir -p "$GOPATH/src/gitlab.cern.ch/flutter"
        - ln -sfv "$(pwd -P)" "$GOPATH/src/gitlab.cern.ch/flutter"
        - cd "$GOPATH/src/gitlab.cern.ch/flutter/fts"
        - make test 

