stages:
    - build
    - image

before_script:
    - curl -fsSLO https://get.docker.com/builds/Linux/x86_64/docker-1.11.2.tgz && tar --strip-components=1 -xvzf docker-1.11.2.tgz -C /usr/local/bin
    - mkdir -p ${GOPATH}/src/gitlab.cern.ch/flutter/
    - ln -s `pwd` ${GOPATH}/src/gitlab.cern.ch/flutter/fts
    - cd ${GOPATH}/src/gitlab.cern.ch/flutter/fts/
    - git remote set-url origin https://gitlab.cern.ch/flutter/fts.git
    - docker login -p "${REGISTRY_PASSWD}" -u "${REGISTRY_USER}" "${CI_REGISTRY}"
after_script:
    - docker logout "${CI_REGISTRY}"

build-schedd:
  image: golang:onbuild
  stage: build
  script:
    - cd schedd
    - go get -v
    - go build -v
    - docker build --pull --no-cache=true --rm=true -t "${CI_REGISTRY_IMAGE}:schedd" .
