database:
  image: fts-db
  container_name: fts-db
  env_file:
    dev.env
  ports:
    - "5432:5432"

broker:
  image: fts-broker
  container_name: fts-broker
  env_file:
    dev.env
  ports:
    - "8161:8161"
    - "61613:61613"

worker:
  image: fts-worker
  links:
    - database
    - broker
  env_file:
    dev.env

sched:
  image: fts-sched
  links:
    - broker
  env_file:
    dev.env

rest:
  image: fts-rest
  links:
    - database
    - broker
  env_file:
    dev.env
  ports:
    - "8446:8446"
  volumes:
    - "${HOME}/.dev-cert:/etc/grid-security/localhost"
