database:
  image: fts-db
  container_name: fts-db
  env_file:
    dev.env
  ports:
    - "15432:5432"

rabbitmq:
  image: rabbitmq:3-management
  container_name: rabbitmq

worker:
  image: fts-worker
  links:
    - database
    - rabbitmq
  env_file:
    dev.env

sched:
  image: fts-sched
  links:
    - rabbitmq
  env_file:
    dev.env

rest:
  image: fts-rest
  links:
    - database
    - rabbitmq
  env_file:
    dev.env
  ports:
    - "8446:8446"
  volumes:
    - "${HOME}/.dev-cert:/etc/grid-security/localhost"
