database:
  image: flutter-dev/db
  container_name: database
  env_file:
    dev.env
  ports:
    - "5432:5432"

broker:
  image: flutter-dev/broker
  container_name: broker 
  env_file:
    dev.env
  ports:
    - "8161:8161"
    - "61613:61613"

worker:
  image: flutter-dev/worker
  links:
    - database
    - broker
  env_file:
    dev.env

sched:
  image: flutter-dev/sched
  links:
    - broker
  env_file:
    dev.env

rest:
  image: flutter-dev/rest
  links:
    - database
    - broker
  env_file:
    dev.env
  ports:
    - "8446:8446"
  volumes:
    - "${HOME}/.dev-cert:/etc/grid-security/localhost"

